- name: Azure Arc for Kubernetes
  href: index.yml
- name: Overview
  href: overview.md
  items:
  - name: Solution architecture
- name: Quickstarts
  expanded: true
  items:
   - name: Connect cluster
     href: connect-a-cluster.md
  items:
   - name: Create cluster with AKS-Engine
     href: connect-a-cluster.md
- name: Tutorials
  expanded: true
  items:
  - name: Use GitOps for AKS clusters
    href: use-gitops.md
  - name: Use GitOps for connected clusters
    href: use-gitops.md
  - name: Deploy IoT workloads
    href: deploy-azure-iot-edge-workloads.md
- name: Concepts
  items:
- name: How-to 
  items:
  - name: Enable resource providers
    href: enable-providers.md
  - name: Install CLI extensions
    href: install-cli-extensions.md
  - name: Security
    items:
    - name: Use Azure Policy
      href: use-azure-policy.md
    - name: Custom service principal
      href: create-onboarding-spn.md
  - name: Monitoring
    items:
    - name: Azure mMnitor for containers
      href: deploy-azure-monitor-for-containers.md
- name: Resources
  items:
  - name: Frequently asked questions
    href: arc-for-Kubernetes-faq.md